// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Login1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login1() {
    driver.get("https://magento.softwaretestingboard.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.linkText("Sign In")).click();
    driver.findElement(By.id("email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.name("password")).sendKeys("radha@12560");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.name("password")).sendKeys("radha@12560");
    driver.findElement(By.id("email")).sendKeys("krishnapatel38@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("patel12236@");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("k23451");
    driver.findElement(By.cssSelector(".primary:nth-child(1) > #send2 > span")).click();
    driver.findElement(By.id("email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.name("password")).sendKeys("radha@12560");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("krishnapatel38@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("patel12236@");
    driver.findElement(By.cssSelector(".login-container")).click();
    driver.findElement(By.cssSelector(".login-container")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".login-container"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("captcha_user_login")).click();
    driver.findElement(By.id("captcha_user_login")).sendKeys("uzze");
    driver.findElement(By.cssSelector(".primary:nth-child(1) > #send2 > span")).click();
    driver.findElement(By.id("email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.name("password")).sendKeys("radha@12560");
    driver.findElement(By.cssSelector(".fieldset:nth-child(2)")).click();
    driver.findElement(By.id("captcha_user_login")).click();
    driver.findElement(By.id("captcha_user_login")).sendKeys("vprq");
    driver.findElement(By.cssSelector(".primary:nth-child(1) > #send2 > span")).click();
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.cssSelector(".header:nth-child(2) > .customer-welcome .action")).click();
    driver.findElement(By.linkText("My Account")).click();
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.cssSelector(".header:nth-child(2) > .customer-welcome .action")).click();
    driver.findElement(By.cssSelector(".page-title-wrapper")).click();
    driver.findElement(By.cssSelector(".header:nth-child(2) > .customer-welcome .action")).click();
    driver.findElement(By.linkText("Sign Out")).click();
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.linkText("Sign In")).click();
    driver.findElement(By.id("email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.name("password")).sendKeys("radha@12560");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("djkekrofmsas");
    driver.findElement(By.cssSelector(".primary:nth-child(1) > #send2 > span")).click();
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.name("password")).sendKeys("radha@12560");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.cssSelector(".primary:nth-child(1) > #send2 > span")).click();
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.cssSelector(".header:nth-child(2) > .customer-welcome .action")).click();
    driver.findElement(By.cssSelector("#ui-id-3 > span")).click();
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.cssSelector("#ui-id-5 > .ui-menu-icon")).click();
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.linkText("Tops")).click();
    {
      WebElement element = driver.findElement(By.linkText("Tops"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".item:nth-child(1) .product-image-photo"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".item:nth-child(2) .product-image-photo"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.cssSelector(".item:nth-child(2) .product-image-photo")).click();
    driver.findElement(By.cssSelector(".item:nth-child(2) .product-image-photo")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".item:nth-child(2) .product-image-photo"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".fotorama__img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,6)");
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("option-label-size-143-item-167")).click();
    driver.findElement(By.id("option-label-color-93-item-50")).click();
    driver.findElement(By.id("qty")).click();
    driver.findElement(By.cssSelector("#product-addtocart-button > span")).click();
    driver.findElement(By.cssSelector(".fieldset > .actions")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".fieldset > .actions"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("product-addtocart-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".qty > .control"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".box-tocart > .fieldset")).click();
    driver.findElement(By.id("tab-label-reviews-title")).click();
    driver.findElement(By.id("nickname_field")).click();
    driver.findElement(By.id("summary_field")).click();
    driver.findElement(By.id("summary_field")).sendKeys("nice");
    driver.findElement(By.id("Rating_1_label")).click();
    driver.findElement(By.id("Rating_1_label")).click();
    {
      WebElement element = driver.findElement(By.id("Rating_1_label"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("review_field")).click();
    driver.findElement(By.id("review_field")).sendKeys("nice product ");
    driver.findElement(By.cssSelector(".submit > span")).click();
    driver.findElement(By.id("customer-email")).sendKeys("dharakachhadiya96@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("radha@12560");
    driver.findElement(By.cssSelector(".showcart")).click();
    driver.findElement(By.linkText("Remove")).click();
    driver.findElement(By.cssSelector(".action-primary")).click();
    driver.findElement(By.id("btn-minicart-close")).click();
    driver.findElement(By.cssSelector(".header:nth-child(2) > .customer-welcome .action")).click();
    driver.findElement(By.linkText("Sign Out")).click();
    driver.close();
  }
}
